import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Activity, ArrowRight, Server, Telescope } from 'lucide-react'
import { AppMetricsPanel } from '@/components/MetricsPanel'
import { IncidentFeed } from '@/components/IncidentFeed'
import { ServiceTable } from '@/components/ServiceTable'
import { ScenarioNarrative } from '@/components/ScenarioPicker'
import { TraceViewer, fromSpanTree } from '@/components/TraceViewer'
import { Button, Panel, PanelHeader, ProvenanceTag, StatusDot } from '@/components/ui/primitives'
import { useIncidents, useMetricCollection, useServices, useSpanTrees } from '@/hooks'
import { recordInteraction } from '@/observability'

export function OverviewPage() {
  const services = useServices()
  const incidents = useIncidents()
  const trees = useSpanTrees()
  const metricCollection = useMetricCollection()
  const [selectedService, setSelectedService] = useState<string | null>(null)

  const realTraces = useMemo(() => trees.slice(0, 8).map(fromSpanTree), [trees])

  useEffect(() => {
    recordInteraction('view-page', 'overview')
  }, [])

  return (
    <>
      <div className="flex flex-wrap items-start justify-between gap-3">
        <ScenarioNarrative />
      </div>

      <div className="grid gap-4 xl:grid-cols-[minmax(0,1.85fr)_minmax(0,1fr)]">
        <div className="flex min-w-0 flex-col gap-4">
          {services.isError ? (
            <Panel className="p-4">
              <p className="text-sm text-crit">
                Failed to load the estate: {services.error.message}
              </p>
            </Panel>
          ) : (
            <ServiceTable
              services={services.data?.services ?? []}
              isLoading={services.isLoading}
              selectedId={selectedService}
              onSelect={setSelectedService}
            />
          )}

          <Panel className="overflow-hidden">
            <PanelHeader
              icon={Telescope}
              title="Recent traces from this browser"
              subtitle="Real spans this tab emitted, most recent first."
              actions={
                <>
                  <ProvenanceTag kind="real" />
                  <Link to="/traces">
                    <Button size="sm" variant="outline">
                      All traces
                      <ArrowRight className="size-3" aria-hidden />
                    </Button>
                  </Link>
                </>
              }
            />
            <div className="[&>section]:rounded-none [&>section]:border-0">
              <TraceViewer
                traces={realTraces}
                emptyTitle="No spans recorded yet"
                emptyDescription={
                  <>
                    Interact with the page — switch scenario, open a route, click a row. The
                    instrumentations registered in <code className="font-mono">src/observability/tracing.ts</code>{' '}
                    will produce spans and they will appear here within a second.
                  </>
                }
              />
            </div>
          </Panel>
        </div>

        <div className="flex min-w-0 flex-col gap-4">
          <AppMetricsPanel
            metrics={metricCollection.metrics}
            history={metricCollection.history}
            collectedAt={metricCollection.collectedAt}
          />

          {incidents.data ? (
            <IncidentFeed incidents={incidents.data.incidents} limit={3} compact />
          ) : (
            <Panel className="p-4">
              <div className="flex items-center gap-2 text-sm text-subtle">
                <Activity className="size-3.5 animate-pulse" aria-hidden />
                Loading incidents…
              </div>
            </Panel>
          )}

          <Panel className="p-4">
            <div className="flex items-start gap-2">
              <Server className="mt-0.5 size-3.5 shrink-0 text-subtle" aria-hidden />
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="text-sm font-semibold text-ink">Where the numbers come from</h3>
                  <StatusDot tone="info" />
                </div>
                <p className="mt-1 text-xs leading-relaxed text-subtle">
                  The fleet table, incident feed and the “Simulated estate” charts are generated by{' '}
                  <code className="font-mono">simulator/</code> and served by the Vercel functions
                  in <code className="font-mono">api/</code>. The “This browser” panel and the trace
                  waterfall above are genuine OpenTelemetry data produced by this tab.
                </p>
              </div>
            </div>
          </Panel>
        </div>
      </div>
    </>
  )
}
