import { useMemo } from 'react'
import {
  Activity,
  BarChart3,
  Gauge,
  MousePointerClick,
  Network,
  Sigma,
  Timer,
} from 'lucide-react'
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip as ChartTooltip,
  XAxis,
  YAxis,
} from 'recharts'
import type { MetricSeries } from '@simulator/types'
import type { MetricHistoryPoint, MetricSnapshot } from '@/observability'
import {
  Badge,
  EmptyState,
  Meter,
  Panel,
  PanelHeader,
  ProvenanceTag,
  Stat,
} from '@/components/ui/primitives'
import { cn, formatCompact, formatDuration, formatNumber, formatPercent } from '@/lib/utils'

/**
 * Two panels that must never be confused with each other, so they are two
 * components with different provenance tags rather than one component with a flag.
 *
 *   AppMetricsPanel      — REAL. Instruments recorded by this browser via the
 *                          OTel SDK, read back out of the SDK's own aggregation
 *                          state. Same numbers that went to the collector.
 *
 *   SimulatedMetricsPanel — FABRICATED. Prometheus-style series generated by
 *                          `simulator/engine.ts`. No real system is involved.
 */

const CHART_MARGIN = { top: 4, right: 8, bottom: 0, left: -18 } as const

/* ── Real: the browser's own instruments ─────────────────────────────────── */

interface TileSpec {
  metricName: string
  label: string
  icon: typeof Activity
  format: (value: number) => string
  hint: string
}

const TILES: readonly TileSpec[] = [
  {
    metricName: 'app.api.client.requests',
    label: 'API calls',
    icon: Network,
    format: (v) => formatNumber(v),
    hint: 'Total calls this tab has made through src/api/client.ts.',
  },
  {
    metricName: 'app.api.client.errors',
    label: 'API errors',
    icon: Activity,
    format: (v) => formatNumber(v),
    hint: 'Calls that failed, by kind. Exported as a counter with error.type.',
  },
  {
    metricName: 'app.ui.interactions',
    label: 'Interactions',
    icon: MousePointerClick,
    format: (v) => formatNumber(v),
    hint: 'User actions the app recorded explicitly.',
  },
  {
    metricName: 'app.spans.emitted',
    label: 'Spans',
    icon: Sigma,
    format: (v) => formatNumber(v),
    hint: 'Spans recorded by this browser, by instrumentation scope.',
  },
]

/** Most recent aggregate value for a metric name. */
function latestValue(metrics: readonly MetricSnapshot[], name: string): number | null {
  const metric = metrics.find((m) => m.name === name)
  if (!metric || metric.points.length === 0) return null

  if (metric.type === 'histogram') {
    let sum = 0
    let count = 0
    for (const point of metric.points) {
      sum += point.sum ?? 0
      count += point.count ?? 0
    }
    return count > 0 ? sum / count : null
  }
  return metric.points.reduce((total, point) => total + (point.value ?? 0), 0)
}

export function AppMetricsPanel({
  metrics,
  history,
  collectedAt,
}: {
  metrics: MetricSnapshot[]
  history: Record<string, MetricHistoryPoint[]>
  collectedAt: number | null
}) {
  const histogram = metrics.find((m) => m.name === 'app.api.client.duration')
  const buckets = useMemo(() => buildBucketDistribution(histogram), [histogram])

  return (
    <Panel className="overflow-hidden">
      <PanelHeader
        icon={Gauge}
        title="This browser"
        subtitle={
          collectedAt
            ? `Pulled from the SDK's own aggregation state · updated ${new Date(collectedAt).toLocaleTimeString('en-US', { hour12: false })}`
            : 'Waiting for the first collection…'
        }
        actions={<ProvenanceTag kind="real" />}
      />

      {metrics.length === 0 ? (
        <EmptyState
          icon={Gauge}
          title="No metric data points yet"
          description="The UI reader collects every two seconds. Interact with the app — switch a scenario or open a page — and instruments will start reporting."
        />
      ) : (
        <>
          <div className="grid grid-cols-2 gap-4 px-4 py-4 lg:grid-cols-4">
            {TILES.map((tile) => {
              const value = latestValue(metrics, tile.metricName)
              const Icon = tile.icon
              return (
                <div key={tile.metricName} className="min-w-0">
                  <Stat
                    label={tile.label}
                    value={
                      <span className="flex items-center gap-1.5">
                        <Icon className="size-4 text-subtle" aria-hidden />
                        {value === null ? '—' : tile.format(value)}
                      </span>
                    }
                    hint={tile.hint}
                  />
                </div>
              )
            })}
          </div>

          <div className="grid gap-4 border-t border-edge px-4 py-4 lg:grid-cols-2">
            <div>
              <div className="mb-2 flex items-center justify-between">
                <span className="text-xs font-medium uppercase tracking-wider text-subtle">
                  API latency · running mean
                </span>
                <span className="font-mono text-2xs text-subtle">app.api.client.duration</span>
              </div>
              <HistoryChart
                points={history['app.api.client.duration'] ?? []}
                tone="accent"
                format={formatDuration}
              />
            </div>

            <div>
              <div className="mb-2 flex items-center justify-between">
                <span className="text-xs font-medium uppercase tracking-wider text-subtle">
                  Latency distribution
                </span>
                <span className="font-mono text-2xs text-subtle">explicit buckets, ms</span>
              </div>
              {buckets.length > 0 ? (
                <div className="h-[120px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={buckets} margin={CHART_MARGIN}>
                      <CartesianGrid stroke="var(--color-edge)" vertical={false} />
                      <XAxis
                        dataKey="label"
                        tick={{ fill: 'var(--color-subtle)', fontSize: 10 }}
                        stroke="var(--color-edge)"
                        interval={0}
                        angle={-30}
                        textAnchor="end"
                        height={38}
                      />
                      <YAxis
                        tick={{ fill: 'var(--color-subtle)', fontSize: 10 }}
                        stroke="var(--color-edge)"
                        allowDecimals={false}
                      />
                      <ChartTooltip content={<ChartTooltipContent unit=" requests" />} />
                      <Bar dataKey="count" fill="var(--color-accent)" radius={[2, 2, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              ) : (
                <p className="py-8 text-center text-sm text-subtle">
                  No histogram recordings yet.
                </p>
              )}
            </div>
          </div>
        </>
      )}
    </Panel>
  )
}

/** Turn explicit histogram buckets into a plottable distribution. */
function buildBucketDistribution(
  metric: MetricSnapshot | undefined,
): Array<{ label: string; count: number }> {
  if (!metric) return []

  // Merge every attribute set into one distribution; a per-route breakdown is
  // available in the raw view but would be unreadable as a bar chart.
  const totals = new Map<string, number>()
  let boundaries: number[] = []

  for (const point of metric.points) {
    if (!point.buckets) continue
    if (point.buckets.boundaries.length > boundaries.length) {
      boundaries = point.buckets.boundaries
    }
  }
  if (boundaries.length === 0) return []

  for (const point of metric.points) {
    if (!point.buckets) continue
    point.buckets.counts.forEach((count, index) => {
      const lower = index === 0 ? 0 : (boundaries[index - 1] ?? 0)
      const upper = boundaries[index]
      const label = upper === undefined ? `>${lower}` : `${lower}–${upper}`
      totals.set(label, (totals.get(label) ?? 0) + count)
    })
  }

  return [...totals.entries()]
    .map(([label, count]) => ({ label, count }))
    .filter((bucket) => bucket.count > 0)
}

function HistoryChart({
  points,
  tone,
  format,
}: {
  points: MetricHistoryPoint[]
  tone: 'accent' | 'crit' | 'ok'
  format: (value: number) => string
}) {
  const colors = {
    accent: 'var(--color-accent)',
    crit: 'var(--color-crit)',
    ok: 'var(--color-ok)',
  }

  if (points.length < 2) {
    return (
      <p className="flex h-[120px] items-center justify-center text-sm text-subtle">
        Collecting… need at least two samples to draw a line.
      </p>
    )
  }

  const data = points.map((point) => ({
    t: point.t,
    v: point.v,
    label: new Date(point.t).toLocaleTimeString('en-US', {
      hour12: false,
      minute: '2-digit',
      second: '2-digit',
    }),
  }))

  return (
    <div className="h-[120px]">
      <ResponsiveContainer width="100%" height="100%">
        <AreaChart data={data} margin={CHART_MARGIN}>
          <defs>
            <linearGradient id={`fill-${tone}`} x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor={colors[tone]} stopOpacity={0.35} />
              <stop offset="100%" stopColor={colors[tone]} stopOpacity={0.02} />
            </linearGradient>
          </defs>
          <CartesianGrid stroke="var(--color-edge)" vertical={false} />
          <XAxis dataKey="label" tick={{ fill: 'var(--color-subtle)', fontSize: 10 }} stroke="var(--color-edge)" minTickGap={24} />
          <YAxis
            tick={{ fill: 'var(--color-subtle)', fontSize: 10 }}
            stroke="var(--color-edge)"
            width={44}
            tickFormatter={(value: number) => format(value)}
          />
          <ChartTooltip content={<ChartTooltipContent format={format} />} />
          <Area
            type="monotone"
            dataKey="v"
            stroke={colors[tone]}
            strokeWidth={1.5}
            fill={`url(#fill-${tone})`}
            isAnimationActive={false}
          />
        </AreaChart>
      </ResponsiveContainer>
    </div>
  )
}

interface TooltipPayloadItem {
  value?: number | string
  payload?: { label?: string; v?: number; count?: number }
}

function ChartTooltipContent({
  active,
  payload,
  format,
  unit,
}: {
  active?: boolean
  payload?: TooltipPayloadItem[]
  format?: (value: number) => string
  unit?: string
}) {
  if (!active || !payload || payload.length === 0) return null
  const item = payload[0]
  if (!item) return null

  const raw = typeof item.value === 'number' ? item.value : Number(item.value ?? 0)

  return (
    <div className="rounded border border-edge-strong bg-raised px-2 py-1.5 text-sm shadow-xl">
      <div className="tnum font-medium text-ink">
        {unit ? `${formatNumber(raw)}${unit}` : format ? format(raw) : formatNumber(raw, 2)}
      </div>
      {item.payload?.label ? (
        <div className="mt-0.5 font-mono text-2xs text-subtle">{item.payload.label}</div>
      ) : null}
    </div>
  )
}

/* ── Simulated: the fabricated estate ────────────────────────────────────── */

const SERIES_COLOURS: Record<string, string> = {
  http_requests_per_second: 'var(--color-accent)',
  http_request_error_rate: 'var(--color-crit)',
  http_request_duration_p95: 'var(--color-warn)',
  http_request_duration_p50: 'var(--color-ok)',
  process_cpu_saturation: 'var(--color-info)',
  cache_hit_ratio: 'var(--color-ok)',
  queue_consumer_lag: 'var(--color-warn)',
  db_connection_pool_utilisation: 'var(--color-accent)',
}

export function SimulatedMetricsPanel({
  series,
  windowMinutes,
  stepSeconds,
}: {
  series: MetricSeries[]
  windowMinutes: number
  stepSeconds: number
}) {
  return (
    <Panel className="overflow-hidden">
      <PanelHeader
        icon={BarChart3}
        title="Simulated estate"
        subtitle={`${series.length} Prometheus-style series · ${windowMinutes}m window at ${stepSeconds}s resolution`}
        actions={<ProvenanceTag kind="simulated" />}
      />

      {series.length === 0 ? (
        <EmptyState
          icon={BarChart3}
          title="No series"
          description="The metrics endpoint returned nothing for this scenario."
        />
      ) : (
        <div className="grid gap-px bg-edge sm:grid-cols-2">
          {series.map((metric) => (
            <SeriesCard key={metric.name} series={metric} />
          ))}
        </div>
      )}
    </Panel>
  )
}

function SeriesCard({ series }: { series: MetricSeries }) {
  const isRatio = series.unit === 'ratio'
  const last = series.points.at(-1)?.v ?? 0
  const first = series.points[0]?.v ?? 0
  const change = first === 0 ? 0 : (last - first) / first
  const colour = SERIES_COLOURS[series.name] ?? 'var(--color-accent)'

  const data = series.points.map((point) => ({
    label: new Date(point.t).toLocaleTimeString('en-US', {
      hour12: false,
      hour: '2-digit',
      minute: '2-digit',
    }),
    v: point.v,
  }))

  const format = (value: number) => (isRatio ? formatPercent(value) : formatCompact(value))

  return (
    <div className="bg-panel px-4 py-3">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="truncate font-mono text-xs text-muted">{series.name}</div>
          <div className="mt-0.5 truncate text-xs text-subtle">{series.description}</div>
        </div>
        <div className="shrink-0 text-right">
          <div className="tnum text-base font-semibold text-ink">{format(last)}</div>
          <div
            className={cn(
              'tnum text-2xs',
              change > 0.02 ? 'text-crit' : change < -0.02 ? 'text-ok' : 'text-subtle',
            )}
          >
            {change >= 0 ? '+' : ''}
            {formatPercent(change, 1)} over window
          </div>
        </div>
      </div>

      <div className="mt-2 h-[86px]">
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart data={data} margin={{ top: 2, right: 4, bottom: 0, left: -24 }}>
            <defs>
              <linearGradient id={`grad-${series.name}`} x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor={colour} stopOpacity={0.3} />
                <stop offset="100%" stopColor={colour} stopOpacity={0.02} />
              </linearGradient>
            </defs>
            <XAxis dataKey="label" hide />
            <YAxis
              tick={{ fill: 'var(--color-subtle)', fontSize: 9 }}
              stroke="var(--color-edge)"
              width={46}
              tickFormatter={(value: number) => format(value)}
            />
            <ChartTooltip content={<ChartTooltipContent format={format} />} />
            <Area
              type="monotone"
              dataKey="v"
              stroke={colour}
              strokeWidth={1.5}
              fill={`url(#grad-${series.name})`}
              isAnimationActive={false}
            />
          </AreaChart>
        </ResponsiveContainer>
      </div>

      <div className="mt-1.5 flex items-center gap-2">
        <Badge tone="neutral" mono>
          {series.unit}
        </Badge>
        <Meter
          value={isRatio ? last : Math.min(1, last / (series.points.reduce((m, p) => Math.max(m, p.v), 1) || 1))}
          tone={isRatio && series.name.includes('error') ? 'crit' : 'accent'}
          className="flex-1"
        />
        <Timer className="size-3 text-subtle" aria-hidden />
      </div>
    </div>
  )
}
